@ECHO OFF

REM "<copyright>"
REM " Copyright 2001-2003 BBNT Solutions, LLC"
REM " under sponsorship of the Defense Advanced Research Projects Agency (DARPA)."
REM ""
REM " This program is free software; you can redistribute it and/or modify"
REM " it under the terms of the Cougaar Open Source License as published by"
REM " DARPA on the Cougaar Open Source Website (www.cougaar.org)."
REM ""
REM " THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS"
REM " PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR"
REM " IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF"
REM " MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT"
REM " ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT"
REM " HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL"
REM " DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,"
REM " TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR"
REM " PERFORMANCE OF THE COUGAAR SOFTWARE."
REM "</copyright>"


set LIBPATHS=
set JAVAFLAGS=


REM Cougaar Desktop
REM set LIBPATHS=%LIBPATHS%;.\bin

set CONFIG_DIR=..\..\data

set LIBPATHS=%LIBPATHS%;%CONFIG_DIR%
set JAVAFLAGS= -DScenarioMap.configDir=%CONFIG_DIR%
set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\mm-mysql-2.jar

set LIBPATHS=%LIBPATHS%;..\..\src
set LIBPATHS=%LIBPATHS%;..\..\src\org\cougaar\lib\uiframework\ui\components

set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\xml4j_2_0_11.jar
set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\core.jar
set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\cuimap.jar
set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\glm.jar
set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\tops.jar
set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\uiframework.jar

REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\classes


REM Cougaar libs
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\aggagent.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\blackjack.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\build.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\contract.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\core.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\delta.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\glm.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\javaiopatch.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\Marine.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\planserver.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\scalability.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\server.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\toolkit.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\tops.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\uiframework.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\lib\vishnu.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\activation.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\chart.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\cuimap.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\fesi-111.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\j2ee.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\jcchart451K.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\jess50.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\jms.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\jndi.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\jsdk.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\mail.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\mm-mysql-2.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\omcore.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\openmap.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\oracle12.zip
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\qslink.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\topsga.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\vgj.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\xalan.jar
REM set LIBPATHS=%LIBPATHS%;%COUGAAR_INSTALL_PATH%\sys\xerces.jar

@ECHO ON

java -mx128m -Djava.compiler=NONE %JAVAFLAGS% -classpath %LIBPATHS% org.cougaar.lib.uiframework.ui.components.desktop.CougaarDesktop
REM java -mx128m %JAVAFLAGS% -classpath %LIBPATHS% org.cougaar.lib.uiframework.ui.components.desktop.CougaarDesktop
